'use strict';

const VERSION = '2.0.0';
const LAKE_CENTER = [44.41123, -83.97949];
const LAKE_BOUNDS = L.latLngBounds([44.3994, -83.9894], [44.4230, -83.9682]);
const CONTOUR_URL = 'https://gisagocss.state.mi.us/arcgis/rest/services/OpenData/hydro/MapServer/4/query';
const EXPORT_URL = 'https://gisagocss.state.mi.us/arcgis/rest/services/OpenData/hydro/MapServer/export';

const map = L.map('map', {preferCanvas:true, zoomControl:true, maxBounds:LAKE_BOUNDS.pad(.65)});
map.fitBounds(LAKE_BOUNDS, {padding:[10,10]});

const street = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  maxZoom:20, attribution:'© OpenStreetMap'
});
const satellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
  maxZoom:20, attribution:'Esri World Imagery'
}).addTo(map);

let contourLayer = null;
let fallbackRaster = null;
let contourFeatures = [];
let labelLayer = L.layerGroup().addTo(map);
let gpsWatch = null;
let gpsMarker = null;
let gpsCircle = null;
let followGps = false;
let majorBreaks = true;
let labelsEnabled = true;

const $ = (id) => document.getElementById(id);
const contourBanner = $('contourBanner');

function arcgisQueryUrl() {
  const b = LAKE_BOUNDS;
  const params = new URLSearchParams({
    f:'geojson',
    where:'1=1',
    geometry:`${b.getWest()},${b.getSouth()},${b.getEast()},${b.getNorth()}`,
    geometryType:'esriGeometryEnvelope',
    inSR:'4326',
    spatialRel:'esriSpatialRelIntersects',
    outFields:'OBJECTID,DEPTH',
    returnGeometry:'true',
    outSR:'4326',
    resultRecordCount:'1000',
    returnExceededLimitFeatures:'true'
  });
  return `${CONTOUR_URL}?${params}`;
}

function mercatorX(lng){ return lng * 20037508.342789244 / 180; }
function mercatorY(lat){
  const y = Math.log(Math.tan((90 + lat) * Math.PI / 360)) / (Math.PI / 180);
  return y * 20037508.342789244 / 180;
}
function rasterUrl(){
  const b=LAKE_BOUNDS;
  const west=mercatorX(b.getWest()), south=mercatorY(b.getSouth());
  const east=mercatorX(b.getEast()), north=mercatorY(b.getNorth());
  const projectedWidth=east-west, projectedHeight=north-south;
  const height=1900, width=Math.round(height*projectedWidth/projectedHeight);
  const p=new URLSearchParams({
    bbox:`${west},${south},${east},${north}`,
    bboxSR:'3857', imageSR:'3857', size:`${width},${height}`,
    dpi:'192', format:'png32', transparent:'true', layers:'show:4', f:'image', v:VERSION
  });
  return `${EXPORT_URL}?${p}`;
}

function depthOf(feature){
  const raw = feature?.properties?.DEPTH ?? feature?.properties?.depth;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

function contourStyle(feature){
  const depth=depthOf(feature);
  const major=majorBreaks && depth !== null && depth % 10 === 0;
  return {color:major?'#0c4d94':'#176eb2', weight:major?2.8:1.35, opacity:.95};
}

async function loadContours(){
  contourBanner.textContent='Loading GPS-aligned depth contours…';
  try{
    const response=await fetch(arcgisQueryUrl(), {cache:'no-store'});
    if(!response.ok) throw new Error(`Contour service returned ${response.status}`);
    const data=await response.json();
    if(!data.features?.length) throw new Error('No contours returned for Rifle Lake');
    contourFeatures=data.features.filter(f=>depthOf(f)!==null);
    if(contourLayer) map.removeLayer(contourLayer);
    contourLayer=L.geoJSON({type:'FeatureCollection',features:contourFeatures},{
      renderer:L.canvas({padding:.4}),
      style:contourStyle,
      onEachFeature:(feature,layer)=>{
        const d=depthOf(feature);
        layer.bindPopup(`<strong>${d} ft contour</strong><br>Michigan Inland Lake Contours`);
      }
    }).addTo(map);
    if(fallbackRaster){map.removeLayer(fallbackRaster);fallbackRaster=null;}
    rebuildLabels();
    contourBanner.textContent=`Depth contours loaded • ${contourFeatures.length} lines`;
    $('sourceNote').textContent='Official Michigan vector contours are aligned by latitude/longitude. Depth labels are generated by this app.';
  }catch(error){
    console.error(error);
    fallbackRaster=L.imageOverlay(rasterUrl(), LAKE_BOUNDS, {opacity:.95,interactive:false,crossOrigin:true}).addTo(map);
    contourBanner.textContent='Contour image fallback loaded • depth numbers unavailable';
    $('labelsToggle').checked=false;
    $('labelsToggle').disabled=true;
    $('sourceNote').textContent='The vector service did not respond, so the app is showing the coordinate-aligned Michigan raster fallback.';
  }
}

function flattenCoordinates(geometry){
  if(!geometry) return [];
  if(geometry.type==='LineString') return geometry.coordinates;
  if(geometry.type==='MultiLineString') return geometry.coordinates.flat();
  return [];
}

function lineLengthPixels(coords){
  let total=0;
  for(let i=1;i<coords.length;i++){
    const a=map.latLngToLayerPoint([coords[i-1][1],coords[i-1][0]]);
    const b=map.latLngToLayerPoint([coords[i][1],coords[i][0]]);
    total+=a.distanceTo(b);
  }
  return total;
}

function labelPoint(coords){
  if(!coords.length) return null;
  return coords[Math.floor(coords.length*0.39)] || coords[Math.floor(coords.length/2)];
}

function rebuildLabels(){
  labelLayer.clearLayers();
  if(!labelsEnabled || !map.hasLayer(labelLayer) || !contourFeatures.length || map.getZoom()<14) return;
  const seen=[];
  const sorted=[...contourFeatures].sort((a,b)=>(depthOf(a)||0)-(depthOf(b)||0));
  for(const feature of sorted){
    const depth=depthOf(feature);
    const coords=flattenCoordinates(feature.geometry);
    if(coords.length<4 || lineLengthPixels(coords)<95) continue;
    const c=labelPoint(coords); if(!c) continue;
    const ll=L.latLng(c[1],c[0]);
    const point=map.latLngToContainerPoint(ll);
    if(seen.some(p=>p.distanceTo(point)<58)) continue;
    seen.push(point);
    L.marker(ll,{interactive:false,icon:L.divIcon({className:'depth-label',html:`${depth}'`,iconSize:[32,19],iconAnchor:[16,9]})}).addTo(labelLayer);
  }
}

function restyleContours(){
  if(contourLayer) contourLayer.setStyle(contourStyle);
}

function pointToSegmentMeters(p,a,b){
  const refLat=p.lat*Math.PI/180;
  const kx=111320*Math.cos(refLat), ky=110540;
  const px=(p.lng-a[0])*kx, py=(p.lat-a[1])*ky;
  const bx=(b[0]-a[0])*kx, by=(b[1]-a[1])*ky;
  const len2=bx*bx+by*by;
  const t=len2 ? Math.max(0,Math.min(1,(px*bx+py*by)/len2)) : 0;
  return Math.hypot(px-t*bx,py-t*by);
}

function nearestContour(latlng){
  let best=null;
  for(const feature of contourFeatures){
    const depth=depthOf(feature);
    const coords=flattenCoordinates(feature.geometry);
    for(let i=1;i<coords.length;i++){
      const meters=pointToSegmentMeters(latlng,coords[i-1],coords[i]);
      if(!best || meters<best.meters) best={depth,meters};
    }
  }
  return best;
}

map.on('click',(event)=>{
  const ll=event.latlng;
  const nearest=nearestContour(ll);
  $('readout').textContent=nearest
    ? `${ll.lat.toFixed(6)}, ${ll.lng.toFixed(6)} • nearest ${nearest.depth} ft contour`
    : `${ll.lat.toFixed(6)}, ${ll.lng.toFixed(6)}`;
  $('nearestDepth').textContent=nearest?`${nearest.depth} ft`:'—';
  $('nearestDistance').textContent=nearest?`${Math.round(nearest.meters)} ft`:'—';
});
map.on('zoomend moveend',rebuildLabels);

$('satelliteToggle').addEventListener('change',(e)=>{
  if(e.target.checked){map.removeLayer(street);satellite.addTo(map);}else{map.removeLayer(satellite);street.addTo(map);}
  if(contourLayer) contourLayer.bringToFront();
  if(fallbackRaster) fallbackRaster.bringToFront();
  labelLayer.bringToFront();
});
$('contoursToggle').addEventListener('change',(e)=>{
  if(e.target.checked){
    if(contourLayer) contourLayer.addTo(map);
    else if(fallbackRaster) fallbackRaster.addTo(map);
    if(labelsEnabled) labelLayer.addTo(map);
  }else{
    if(contourLayer) map.removeLayer(contourLayer);
    if(fallbackRaster) map.removeLayer(fallbackRaster);
    map.removeLayer(labelLayer);
  }
});
$('labelsToggle').addEventListener('change',(e)=>{
  labelsEnabled=e.target.checked;
  if(labelsEnabled && $('contoursToggle').checked){labelLayer.addTo(map);rebuildLabels();}
  else map.removeLayer(labelLayer);
});
$('majorToggle').addEventListener('change',(e)=>{majorBreaks=e.target.checked;restyleContours();});
$('lakeButton').addEventListener('click',()=>map.fitBounds(LAKE_BOUNDS,{padding:[10,10]}));
$('followButton').addEventListener('click',()=>{
  followGps=!followGps;
  $('followButton').classList.toggle('active',followGps);
  $('followButton').textContent=followGps?'Following':'Follow';
  if(followGps && gpsMarker) map.setView(gpsMarker.getLatLng(),17);
});

function gpsQuality(accuracy){
  if(accuracy<=5) return ['Excellent','#67d1b6'];
  if(accuracy<=10) return ['Good','#67d1b6'];
  if(accuracy<=20) return ['Fair','#f3c969'];
  return ['Poor','#ff8e79'];
}

$('gpsButton').addEventListener('click',()=>{
  if(gpsWatch!==null){
    navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null;
    $('gpsButton').textContent='Use GPS';$('gpsBanner').textContent='GPS off';
    return;
  }
  if(!navigator.geolocation){$('gpsBanner').textContent='GPS unsupported';return;}
  $('gpsBanner').textContent='Acquiring precise location…';
  gpsWatch=navigator.geolocation.watchPosition((position)=>{
    const {latitude,longitude,accuracy}=position.coords;
    const ll=L.latLng(latitude,longitude);
    const [quality,color]=gpsQuality(accuracy);
    $('gpsBanner').textContent=`${quality} GPS • ±${Math.round(accuracy)} m`;
    $('gpsBadge').textContent=quality;$('gpsBadge').style.color=color;
    $('accuracyValue').textContent=`±${Math.round(accuracy)} m`;
    $('coordinateValue').textContent=`${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;
    if(!gpsCircle){
      gpsCircle=L.circle(ll,{radius:accuracy,color:'#43a8ff',weight:2,fillColor:'#43a8ff',fillOpacity:.12}).addTo(map);
      gpsMarker=L.circleMarker(ll,{radius:8,color:'#fff',weight:3,fillColor:'#1679ff',fillOpacity:1}).addTo(map);
    }else{
      gpsCircle.setLatLng(ll).setRadius(accuracy);gpsMarker.setLatLng(ll);
    }
    $('gpsButton').textContent='Stop GPS';
    if(followGps) map.setView(ll,Math.max(17,map.getZoom()),{animate:true});
  },(error)=>{
    $('gpsBanner').textContent=error.code===1?'Location permission denied':'Unable to get GPS';
  },{enableHighAccuracy:true,maximumAge:0,timeout:20000});
});

loadContours();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v='+VERSION).catch(console.error));}
